<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '&copy; {year}, made by {company}' => '&copy; {year}, Minden jog fenntartva {company}',
    'Actions' => 'Műveletek',
    'Are you sure you want to delete this item?' => 'Biztosan törli ezt az elemet?',
    'Are you sure? Deleted user can not be restored' => '',
    'Back' => '',
    'Change account' => '',
    'Change password' => '',
    'Create User' => '',
    'Create new {modelName}' => '',
    'Delete' => '',
    'Edit profile' => '',
    'Email' => '',
    'Email address' => '',
    'Error occurred while changing password' => '',
    'Error occurred while deleting user' => '',
    'First' => '',
    'Go back' => '',
    'Incorrect old password.' => '',
    'Incorrect username or password.' => '',
    'Last' => '',
    'Lock' => '',
    'Locked account' => '',
    'Log out' => '',
    'Login' => '',
    'Next' => '',
    'Ooooups! Looks like you got lost.' => '',
    'Password' => '',
    'Password has been changed' => '',
    'Please fix following errors:' => '',
    'Prev' => '',
    'Profile' => '',
    'Reset filters' => '',
    'Save' => '',
    'Save changes' => '',
    'Sign In' => '',
    'Sign in' => '',
    'Successfully saved!' => '',
    'The requested page does not exist.' => '',
    'Update' => '',
    'Update User: {name}' => '',
    'User' => '',
    'User has been created' => 'A felhasználó sikeresen létre lett hozva',
    'User has been deleted' => '',
    'User is not found' => '',
    'Username' => '',
    'Users' => '',
    'View' => '',
    'Wrong password' => '',
    'You have successfully created the item!' => '',
    'You have successfully modified the item!' => '',
    'You have successfully removed the item!' => '',
];
