<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '&copy; {year}, made by {company}' => '&copy; {year}, Minden jog fenntartva {company}',
    'Are you sure to delete this {item}?' => 'Biztosan törli ezt az {item} elemet?',
    'Back to login' => 'Vissza a belépésre',
    'Change account' => 'Fiók módosítása',
    'First' => 'Első',
    'Forgot your password?' => 'Elfelejtette a jelszavát?',
    'Go back' => 'Visszalépés',
    'Last' => 'Utolsó',
    'Lock' => 'Lezár',
    'Locked account' => 'Lezárt fiók',
    'Log out' => 'Kilépés',
    'Login' => 'Belépés',
    'Next' => 'Következő',
    'No' => 'Nem',
    'Not selected' => 'Nincs kiválasztva',
    'Ooooups! Looks like you got lost.' => 'Hoppá! Úgy tűnik, eltévedtél.',
    'Prev' => 'Előző',
    'Profile' => 'Profil',
    'Reset password' => 'Jelszó törlése',
    'Send email' => 'E-mail küldése',
    'Sign in' => 'Belépés',
    'Yes' => 'Igen',
    'item' => 'tétel',
    'Are you sure you want to delete this item?' => 'Biztos törölni szeretnéd ezt a tételt?',
    'Back' => 'Vissza',
    'Create' => 'Létrehozás',
    'Delete' => 'Törlés',
    'Excel export' => 'Excel exportálás',
    'New {{modelTitle}}' => 'Új {{modelTitle}}',
    'Reset filters' => 'Szűrések törlése',
    'Save' => 'Mentés',
];
