<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '&copy; {year}, made by {company}' => '&copy; {year}, made by {company}',
    'Are you sure to delete this {item}?' => 'Are you sure to delete this {item}?',
    'Are you sure you want to delete this item?' => 'Are you sure you want to delete this item?',
    'Back' => 'Back',
    'Back to login' => 'Back to login',
    'Change account' => 'Change account',
    'Create' => 'Create',
    'Delete' => 'Delete',
    'Excel export' => 'Excel export',
    'First' => 'First',
    'Forgot your password?' => 'Forgot your password?',
    'Go back' => 'Go back',
    'Item successfully created!' => 'Item successfully created!',
    'Last' => 'Last',
    'Lock' => 'Lock',
    'Locked account' => 'Locked account',
    'Log out' => 'Log out',
    'Login' => 'Login',
    'New {model} create' => 'New {model} create',
    'New {{modelTitle}}' => 'New {{modelTitle}}',
    'Next' => 'Next',
    'No' => 'No',
    'Not selected' => 'Not selected',
    'Ooooups! Looks like you got lost.' => 'Ooooups! Looks like you got lost.',
    'Prev' => 'Prev',
    'Profile' => 'Profile',
    'Reset filters' => 'Reset filters',
    'Reset password' => 'Reset password',
    'Save' => 'Save',
    'Send email' => 'Send email',
    'Sign in' => 'Sign in',
    'Yes' => 'Yes',
    'You have successfully modified the item!' => 'You have successfully modified the item!',
    'You have successfully removed the item!' => 'You have successfully removed the item!',
    'item' => 'item',
    '{model} edit' => '{model} edit',
    'More' => 'More',
];
