<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '&copy; {year}, made by {company}' => '&copy; {year}, made by {company}',
    'Actions' => 'Actions',
    'Are you sure you want to delete this item?' => 'Are you sure you want to delete this item?',
    'Are you sure? Deleted user can not be restored' => 'Are you sure? Deleted user can not be restored',
    'Back' => 'Back',
    'Change account' => 'Change account',
    'Change password' => 'Change password',
    'Create User' => 'Create User',
    'Create new {modelName}' => 'Create new {modelName}',
    'Delete' => 'Delete',
    'Edit profile' => 'Edit profile',
    'Email' => 'Email',
    'Email address' => 'Email address',
    'Error occurred while changing password' => 'Error occurred while changing password',
    'Error occurred while deleting user' => 'Error occurred while deleting user',
    'First' => 'First',
    'Go back' => 'Go back',
    'Incorrect old password.' => 'Incorrect old password.',
    'Incorrect username or password.' => 'Incorrect username or password.',
    'Last' => 'Last',
    'Lock' => 'Lock',
    'Locked account' => 'Locked account',
    'Log out' => 'Log out',
    'Login' => 'Login',
    'Next' => 'Next',
    'Ooooups! Looks like you got lost.' => 'Ooooups! Looks like you got lost.',
    'Password' => 'Password',
    'Password has been changed' => 'Password has been changed',
    'Please fix following errors:' => 'Please fix following errors:',
    'Prev' => 'Prev',
    'Profile' => 'Profile',
    'Reset filters' => 'Reset filters',
    'Save' => 'Save',
    'Save changes' => 'Save changes',
    'Sign In' => 'Sign In',
    'Sign in' => 'Sign in',
    'Successfully saved!' => 'Successfully saved!',
    'The requested page does not exist.' => 'The requested page does not exist.',
    'Update' => 'Update',
    'Update User: {name}' => 'Update User: {name}',
    'User' => 'User',
    'User has been created' => 'User has been created',
    'User has been deleted' => 'User has been deleted',
    'User is not found' => 'User is not found',
    'Username' => 'Username',
    'Users' => 'Users',
    'View' => 'View',
    'Wrong password' => 'Wrong password',
    'You have successfully created the item!' => 'You have successfully created the item!',
    'You have successfully modified the item!' => 'You have successfully modified the item!',
    'You have successfully removed the item!' => 'You have successfully removed the item!',
    'Active' => 'Active',
    'All' => 'All',
    'Deleted' => 'Deleted',
    'Inactive' => 'Inactive',
    'New password' => 'New password',
    'No' => 'No',
    'Old password' => 'Old password',
    'Retype password' => 'Retype password',
    'Yes' => 'Yes',
];
