<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '&copy; {year}, made by {company}' => '&copy; {year}, made by {company}',
    'Are you sure to delete this {item}?' => 'Are you sure to delete this {item}?',
    'Change account' => 'Change account',
    'First' => 'First',
    'Go back' => 'Go back',
    'Last' => 'Last',
    'Lock' => 'Lock',
    'Locked account' => 'Locked account',
    'Log out' => 'Log out',
    'Login' => 'Login',
    'Next' => 'Next',
    'Ooooups! Looks like you got lost.' => 'Ooooups! Looks like you got lost.',
    'Prev' => 'Prev',
    'Profile' => 'Profile',
    'Sign in' => 'Sign in',
    'item' => 'item',
    'Back to login' => 'Back to login',
    'Forgot your password?' => 'Forgot your password?',
    'Reset password' => 'Reset password',
    'Send email' => 'Send email',
];
